name: chtulhu
on:
  push:
    branches: [ devellop ] 
jobs:
  ansible:
    name: run playbook
    runs-on: [self-hosted, yig]
    steps:
      # Checkout : récupère le projet à jour depuis le dépôt : comme un git clone | pull
      - name: Checkout du dépôt
        uses: actions/checkout@v7
        # ansible ansible ansible ! WHYYYYYYYY ?
      - name: injection des vaults
        working-directory: ${{ github.workspace }}
        run: |
          cp /home/ansible/git/ansible/inventory/staging/group_vars/vault.yml /home/ansible/git/ansible/ansible/ansible/inventory/staging/group_vars/vault.yml
      - name: run ansible-playbook
        working-directory: ${{ github.workspace }}
        run: |
          ansible-playbook main.yml